sudo: required
language: python
python:
    - 3.6.8
if: branch = master OR tag IS present
script:
  - pip install -r requirements.txt
  - git clone https://github.com/lnls-sirius/eth-bridge-pru-serial485.git
  - cd eth-bridge-pru-serial485/client
  - python setup.py install
  - cd ../../
  - git clone https://github.com/lnls-fac/mathphys.git
  - cd mathphys
  - python setup.py install
  - cd ../
  - cd siriuspy
  - python setup.py test

# safelist
branches:
  only:
  - master

